jobs:
  check:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./verify/ci

name: Check

on:
  schedule:
    - cron: "45 */6 * * *"
